Add bracket support and 判斷 method
nk2028/qieyun-encoder pull request #2
Opened 2021-04-30 17:59 UTC by graphemecluster

Now adding spaces between each expression becomes optional.
Additionally, a better example should be prepared for the 判斷 method.

2021-04-30 18:15 UTC, graphemecluster commented
已經 run 過 pytest 冇問題
當然您試多幾嘢先好 merge。
話説第 458 行寫「用戶」、「用户」定「使用者」好？

2021-05-01 01:05 UTC, ayaka14732 commented
可唔可以幫手加多啲 test？

如果跟 OpenCC 標準就係「用戶」，但其實呢度可以換個講法，冇必要用到呢個詞～

2021-05-02 18:40 UTC, graphemecluster commented
喺 qieyun-js 抄咗啲 test 過嚟，另外加多咗屬於同判斷嘅 test。（我諗唔到好嘅例子）
加多咗個 property 叫「韻別」，傳回陰、陽定入聲韻。（名係暫定，你改個好啲嘅名）
加次入韻順手加埋輕脣韻，我見你常量嗰度定義咗。

感覺唔係好 keep 到你個 coding style，你改下好啲。

2021-05-03 02:11 UTC, ayaka14732 commented
表達式嗰度好似加咗好多嘢，可唔可以 document 下具體用法？

2021-05-04 23:50 UTC, graphemecluster commented
OK，Update 咗個 doc，你睇下有咩唔鍾意或者表達不清嘅地方改下

2021-05-05 00:15 UTC, graphemecluster commented
仲有一樣嘢，字典理論上會以順次序執行落去，如果有人真係驚嘅話可以用 OrderedDict
（好似話由 Python 3.6 開始已經係順次序，不過 3.7 先寫落 spec，所以 OrderedDict 其實無用）

2021-05-05 00:25 UTC, ayaka14732 commented
我諗咗下空格仲係必要嘅，可以提升可讀性，而且唔加空格有時會有歧義

比如以後可以加入處理「非組」，識別到「非組」就報錯「請使用幫組 輕脣韻」，噉如果用户寫「非見組」就有歧義

2021-05-05 00:36 UTC, ayaka14732 requested changes

2021-05-05 00:36 UTC, ayaka14732 commented on src/QieyunEncoder/常量.py
> +    所有音: str = '脣舌牙齒喉'
```suggestion
    所有音: str = '脣舌齒牙喉'
```

牙喉係一類，所以推導嗰陣通常係呢個順序

2021-05-05 00:36 UTC, ayaka14732 commented on src/QieyunEncoder/常量.py
> +    陰聲韻: str = '支脂之微魚虞模齊佳皆灰咍祭泰夬廢蕭宵肴豪歌戈麻侯尤幽'
```suggestion
    陰聲韻: str = '支脂之微魚虞模齊祭泰佳皆夬灰咍廢蕭宵肴豪歌麻侯尤幽'
```

排序、刪咗戈韻（廣韻有但係切韻冇）

2021-05-05 00:43 UTC, graphemecluster commented on src/QieyunEncoder/常量.py
> +    所有音: str = '脣舌牙齒喉'
我齋 copy & paste 冇望到個順序 😅

2021-05-06 21:24 UTC, graphemecluster commented
噉我到時加返空格先再開返個 PR，我諗我要暫時唞下

2021-05-06 21:24 UTC, closed without merging